### ISSUE TITLE
Copyright/License

### ISSUE THREAD

**Issue by spelufo** [scheme/scsh#34]
I'm making a package for this project for Arch Linux, and I have to include a license. Is [this][1] it? This is a continuation of that scsh, right? Or did you start over?

Maybe you could include a COPYING file with the contents of that page.

Thanks.

[1]: http://scsh.net/docu/copying.html

**Comment by roderyc** [comment]
Correct; that's the license and this is a continuation. You're right, there should be a file with the license in this repo. I'll add it in a bit. Thanks.
